use std::env;
use std::fs;
use std::path::PathBuf;
use std::process::Command;

/// Locate MSVC lib.exe for generating import libraries
fn find_lib_exe() -> PathBuf {
    // Try common VS2022 paths
    let candidates = [
        r"C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC",
        r"C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC",
        r"C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC",
    ];
    for base in &candidates {
        if let Ok(entries) = std::fs::read_dir(base) {
            for entry in entries.flatten() {
                let path = entry.path().join("bin").join("Hostx64").join("x64").join("lib.exe");
                if path.exists() {
                    return path;
                }
            }
        }
    }
    // Fallback: hope it's in PATH
    PathBuf::from("lib.exe")
}

fn main() {
    let gfortran = env::var("GFORTRAN").unwrap_or_else(|_| "gfortran".to_string());
    let fortran_dir = PathBuf::from("src").join("fortran");
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());

    // --- Dependency-ordered source list ---
    //   avx512_math must be first! Other modules use it
    let sources: Vec<&str> = vec![
        "avx512_math.f90",  // ★ Must be first! Other modules use it
        "blas.f90",
        "activation.f90",
        "loss.f90",
        "norm.f90",
        "conv.f90",
        "scipy_openblas.f90",  // ★ scipy OpenBLAS wrapper
        "c_bridge.f90",
    ];

    // === Merge all Fortran into one source file ===
    let combined_path = out_dir.join("fortran_all.f90");
    let mut combined = String::new();
    combined.push_str("! Auto-generated by build.rs\n\n");
    for src in &sources {
        let src_path = fortran_dir.join(src);
        let content = fs::read_to_string(&src_path)
            .expect(&format!("Failed to read {}", src_path.display()));
        combined.push_str(&format!("! === {src} ===\n"));
        combined.push_str(&content);
        combined.push('\n');
    }
    fs::write(&combined_path, &combined).expect("Failed to write combined Fortran source");

    // === Compile Fortran to shared library ===
    // Windows: DLL + lib.exe import library + MSVC link
    // Linux:   .so (auto-linked by Rust)
    // macOS:   .dylib
    //
    // Naming convention:
    //   - Windows DLL must be named `fortran_core.dll` (lib.exe companion .lib)
    //   - Linux/macOS shared lib must be named `libfortran_core.so/.dylib` for rustc `-lfortran_core` to find
    #[cfg(target_os = "windows")]
    let (lib_filename, link_kind) = ("fortran_core.dll", "fortran_core");
    #[cfg(not(target_os = "windows"))]
    let (lib_filename, link_kind) = ("libfortran_core.so", "fortran_core");

    let lib_path = out_dir.join(lib_filename);

    let mut cmd = Command::new(&gfortran);
    cmd.args(["-shared"]);           // Win→DLL, Linux→.so, mac→.dylib
    cmd.args(["-Ofast", "-fPIC"]);
    // Linux/macOS: let shared lib declare SONAME, runtime dlopen finds by lib name
    #[cfg(not(target_os = "windows"))]
    cmd.args([format!("-Wl,-soname,{}", lib_filename).as_str()]);
    cmd.args(["-funroll-loops", "-ftree-vectorize"]);
    // ★ Universal portable ISA: x86-64-v3 (Haswell 2013+)
    //   Includes AVX2 + FMA + BMI2, supported by almost all x86 CPUs since 2015.
    //   No hand-written intrinsics needed at compile time; let gfortran auto-generate SIMD FMA code.
    //   Don't use -march=native, which makes the binary non-portable to other machines.
    cmd.args(["-march=x86-64-v3", "-mtune=generic"]);  // ★ AVX2 + FMA (Haswell+, safe portable)
    cmd.args(["-std=f2018"]);
    // ★ Round-18: explicit free-form (avoid gfortran misdetecting fixed-form and suppressing OMP sentinel directives)
    cmd.args(["-ffree-form"]);
    // OpenMP multi-threading
    cmd.args(["-fopenmp"]);
    // ★ math library: -fopenmp-simd puts exp/log/sqrt etc. into SIMD reduction
    //   This lets softmax's exp() and layernorm's sqrt() use vector instructions
    cmd.args(["-fopenmp-simd"]);
    // IPO flags within single TU
    cmd.args([
        "-fipa-cp", "-fipa-cp-clone",
        "-fipa-sra", "-fipa-icf",
        "-fdevirtualize-speculatively",
        "-finline-functions", "-findirect-inlining",
        "-finline-small-functions", "-finline-functions-called-once",
        "-ftree-loop-vectorize", "-ftree-slp-vectorize",
        "-fvect-cost-model=very-cheap",  // Encourage SIMD
    ]);
    // Static-link Fortran runtime:
    //   - Windows: needed (avoid depending on gfortran DLL; static lib is PIC, can link into DLL)
    //   - Linux: cannot! Debian/Ubuntu static libgfortran.a is non-PIC, linking into .so will fail
    #[cfg(target_os = "windows")]
    cmd.args(["-static-libgfortran", "-static-libgcc"]);
    // Export all symbols (Windows: via .def; Linux/macOS: via default linker behaviour)
    #[cfg(target_os = "windows")]
    cmd.args([
        "-Wl,--output-def", out_dir.join("fortran_core.def").to_str().unwrap(),
        "-Wl,--export-all-symbols",
        "-Wl,--enable-auto-import",
    ]);

    // === Copy OpenBLAS DLL before linking ===
    #[cfg(target_os = "windows")]
    {
        let scipy_libs = std::path::Path::new(
            &env::var("VIRTUAL_ENV").unwrap_or_else(|_| ".venv".to_string())
        ).join("Lib").join("site-packages").join("scipy.libs");
        if scipy_libs.exists() {
            for entry in std::fs::read_dir(&scipy_libs).unwrap() {
                let path = entry.unwrap().path();
                if path.extension().map_or(false, |e| e == "dll") {
                    let dest = out_dir.join("openblas.dll");
                    std::fs::copy(&path, &dest).ok();
                    println!("cargo:warning=OpenBLAS DLL copied: {}", dest.display());
                    break;
                }
            }
        }
    }

    cmd.args(["-J", out_dir.to_str().unwrap(),
        "-L", out_dir.to_str().unwrap(),
        "-l:openblas.dll",                  // ★ Direct link DLL (MinGW)
        "-Wl,--enable-auto-import",         // ★ Allow auto-import
        "-o", lib_path.to_str().unwrap(),
        combined_path.to_str().unwrap(),
    ]);

    let status = cmd.status().expect("Failed to run gfortran");
    if !status.success() {
        panic!("gfortran shared lib build failed");
    }
    println!("cargo:warning=Fortran shared library built: {}", lib_path.display());

    // === Generate MSVC import library (Windows-only) ===
    #[cfg(target_os = "windows")]
    {
        let lib_exe = find_lib_exe();
        let import_path = out_dir.join("fortran_core.lib");
        let lib_status = Command::new(&lib_exe)
            .args([
                format!("/def:{}", out_dir.join("fortran_core.def").display()),
                format!("/out:{}", import_path.display()),
                "/machine:x64".to_string(),
            ])
            .status()
            .expect(&format!("Failed to run {}", lib_exe.display()));

        if !lib_status.success() {
            panic!("lib.exe failed to create import library");
        }
        println!("cargo:warning=Import library created: {}", import_path.display());
    }

    // --- Link ---
    println!("cargo:rustc-link-search=native={}", out_dir.display());
    println!("cargo:rustc-link-lib={}", link_kind); // win: fortran_core.lib; unix: dylib=fortran_core.so

    println!("cargo:rustc-link-lib=openblas");

    // ★ Round-16: LLVM AVX-512 SIMD (512-bit, 8-wide f64)
    println!("cargo:rustc-env=RUSTFLAGS=-C target-cpu=x86-64-v3");

    // ★★★ Linux cloud: link OpenBLAS + set NUMA affinity ★★★
    // OpenBLAS will auto-select per-CPU optimal GEMM kernel (SKX/ZN 4 etc.)
    if env::consts::OS == "linux" {
        // gfortran-generated Fortran runtime shared libraries (libgfortran.so / libgomp.so)
        //   Must be explicitly told to rustc, otherwise runtime dlopen fails
        println!("cargo:rustc-link-lib=dylib=gfortran");
        println!("cargo:rustc-link-lib=dylib=gomp");
        // OpenBLAS with multithreading (uses OpenMP internally)
        println!("cargo:rustc-link-lib=dylib=openblas");
        // Environment variables: bind OpenBLAS threads to physical cores
        println!("cargo:rustc-env=OMP_PLACES=cores");
        println!("cargo:rustc-env=OMP_PROC_BIND=close");
        println!("cargo:rustc-env=GOTO_NUM_THREADS={}", num_cpus::get());
        println!("cargo:rustc-env=OPENBLAS_NUM_THREADS={}", num_cpus::get());
        // Enable AVX-512 VNNI (Intel Deep Learning Boost)
        println!("cargo:rustc-env=OPENBLAS_LOOPS=avx512");
        // OpenBLAS dynamically selects optimal kernel
        println!("cargo:rustc-env=OPENBLAS_MAIN_FREE=1");
        println!("cargo:rustc-env=OPENBLAS_VERBOSE=0");
    }

    for f in &sources {
        println!("cargo:rerun-if-changed={}", fortran_dir.join(f).display());
    }
    println!("cargo:rerun-if-changed=build.rs");
}