use std::env;
use std::fs;
use std::path::PathBuf;
use std::process::Command;

/// Locate MSVC lib.exe for generating import libraries
fn find_lib_exe() -> PathBuf {
    // Try common VS2022 paths
    let candidates = [
        r"C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC",
        r"C:\Program Files\Microsoft Visual Studio\2022\Professional\VC\Tools\MSVC",
        r"C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC",
    ];
    for base in &candidates {
        if let Ok(entries) = std::fs::read_dir(base) {
            for entry in entries.flatten() {
                let path = entry.path().join("bin").join("Hostx64").join("x64").join("lib.exe");
                if path.exists() {
                    return path;
                }
            }
        }
    }
    // Fallback: hope it's in PATH
    PathBuf::from("lib.exe")
}

fn main() {
    let gfortran = env::var("GFORTRAN").unwrap_or_else(|_| "gfortran".to_string());
    let fortran_dir = PathBuf::from("src").join("fortran");
    let out_dir = PathBuf::from(env::var("OUT_DIR").unwrap());

    // --- Dependency-ordered source list ---
    //   avx512_math 必须第一！其他模块 use 它
    let sources: Vec<&str> = vec![
        "avx512_math.f90",  // ★ Round-16: 手写 AVX-512 exp/log kernel (must be first!)
        "blas.f90",
        "activation.f90",
        "loss.f90",
        "norm.f90",
        "conv.f90",
        "c_bridge.f90",
    ];

    // === Merge all Fortran into one source file ===
    let combined_path = out_dir.join("fortran_all.f90");
    let mut combined = String::new();
    combined.push_str("! Auto-generated by build.rs\n\n");
    for src in &sources {
        let src_path = fortran_dir.join(src);
        let content = fs::read_to_string(&src_path)
            .expect(&format!("Failed to read {}", src_path.display()));
        combined.push_str(&format!("! === {src} ===\n"));
        combined.push_str(&content);
        combined.push('\n');
    }
    fs::write(&combined_path, &combined).expect("Failed to write combined Fortran source");

    // === Compile Fortran to shared library ===
    // Windows: DLL + lib.exe import library + MSVC link
    // Linux:   .so (auto-linked by Rust)
    // macOS:   .dylib
    //
    // 命名规范：
    //   - Windows DLL 必须叫 `fortran_core.dll`（lib.exe 配套 .lib）
    //   - Linux/macOS 共享库必须叫 `libfortran_core.so/.dylib` 才能被 rustc `-lfortran_core` 找到
    #[cfg(target_os = "windows")]
    let (lib_filename, link_kind) = ("fortran_core.dll", "fortran_core");
    #[cfg(not(target_os = "windows"))]
    let (lib_filename, link_kind) = ("libfortran_core.so", "fortran_core");

    let lib_path = out_dir.join(lib_filename);

    let mut cmd = Command::new(&gfortran);
    cmd.args(["-shared"]);           // Win→DLL, Linux→.so, mac→.dylib
    cmd.args(["-O3", "-fPIC"]);
    // Linux/macOS: 让共享库自报 SONAME，运行时 dlopen 用 lib 名查找
    #[cfg(not(target_os = "windows"))]
    cmd.args([format!("-Wl,-soname,{}", lib_filename).as_str()]);
    cmd.args(["-ffast-math", "-funroll-loops", "-ftree-vectorize"]);
    // ★ 允许编译器重排数学运算 + 让 exp/log 向量化 (SIMD)
    cmd.args(["-fno-math-errno", "-fno-trapping-math", "-funsafe-math-optimizations"]);
    // ★ 通用可移植指令集：x86-64-v3 (Haswell 2013+)
    //   包含 AVX2 + FMA + BMI2，几乎所有 2015 年后的 x86 CPU 都支持。
    //   编译时无需写手写 intrinsics，让 gfortran 自动生成 SIMD FMA 代码。
    //   不用 -march=native，因为那会让二进制无法在其他机器跑。
    cmd.args(["-march=x86-64-v4", "-mtune=generic"]);  // ★ Round-16: AVX-512 (512-bit SIMD, 8-wide f64)
    cmd.args(["-std=f2018"]);
    // ★ Round-18: 显式 free-form（避免 gfortran 误判 fixed-form 抑制 sentinel OMP 指令）
    cmd.args(["-ffree-form"]);
    // OpenMP 多线程
    cmd.args(["-fopenmp"]);
    // ★ math library: -fopenmp-simd 把 exp/log/sqrt 等放进 SIMD reduction
    //   这样 softmax 的 exp() 和 layernorm 的 sqrt() 会用向量指令
    cmd.args(["-fopenmp-simd"]);
    // IPO flags within single TU
    cmd.args([
        "-fipa-cp", "-fipa-cp-clone",
        "-fipa-sra", "-fipa-icf",
        "-fdevirtualize-speculatively",
        "-finline-functions", "-findirect-inlining",
        "-finline-small-functions", "-finline-functions-called-once",
        "-ftree-loop-vectorize", "-ftree-slp-vectorize",
        "-fvect-cost-model=very-cheap",  // 鼓励 SIMD
    ]);
    // Static-link Fortran runtime:
    //   - Windows: 需要（避免依赖 gfortran DLL；静态 lib 是 PIC，可链进 DLL）
    //   - Linux: 不能！Debian/Ubuntu 静态 libgfortran.a 是非 PIC，链进 .so 会失败
    #[cfg(target_os = "windows")]
    cmd.args(["-static-libgfortran", "-static-libgcc"]);
    // Export all symbols (Windows: via .def; Linux/macOS: via default linker behaviour)
    #[cfg(target_os = "windows")]
    cmd.args([
        "-Wl,--output-def", out_dir.join("fortran_core.def").to_str().unwrap(),
        "-Wl,--export-all-symbols",
        "-Wl,--enable-auto-import",
    ]);

    cmd.args([
        "-J", out_dir.to_str().unwrap(),
        "-o", lib_path.to_str().unwrap(),
        combined_path.to_str().unwrap(),
    ]);

    let status = cmd.status().expect("Failed to run gfortran");
    if !status.success() {
        panic!("gfortran shared lib build failed");
    }
    println!("cargo:warning=Fortran shared library built: {}", lib_path.display());

    // === Generate MSVC import library (Windows-only) ===
    #[cfg(target_os = "windows")]
    {
        let lib_exe = find_lib_exe();
        let import_path = out_dir.join("fortran_core.lib");
        let lib_status = Command::new(&lib_exe)
            .args([
                format!("/def:{}", out_dir.join("fortran_core.def").display()),
                format!("/out:{}", import_path.display()),
                "/machine:x64".to_string(),
            ])
            .status()
            .expect(&format!("Failed to run {}", lib_exe.display()));

        if !lib_status.success() {
            panic!("lib.exe failed to create import library");
        }
        println!("cargo:warning=Import library created: {}", import_path.display());
    }

    // --- Link ---
    println!("cargo:rustc-link-search=native={}", out_dir.display());
    println!("cargo:rustc-link-lib={}", link_kind); // win: fortran_core.lib; unix: dylib=fortran_core.so

    // ★ Round-16: LLVM AVX-512 SIMD (512-bit, 8-wide f64)
    println!("cargo:rustc-env=RUSTFLAGS=-C target-cpu=x86-64-v4");

    // ★★★ Linux 云端：链接 OpenBLAS + 设置 NUMA 亲和性 ★★★
    // OpenBLAS 会自动选择 per-CPU 最优 GEMM kernel（SKX/ZN 4 等）
    if env::consts::OS == "linux" {
        // gfortran 生成的 Fortran runtime 共享库（libgfortran.so / libgomp.so）
        //   必须显式告诉 rustc，否则运行时 dlopen 失败
        println!("cargo:rustc-link-lib=dylib=gfortran");
        println!("cargo:rustc-link-lib=dylib=gomp");
        // OpenBLAS with multithreading (uses OpenMP internally)
        println!("cargo:rustc-link-lib=dylib=openblas");
        // 环境变量：让 OpenBLAS 绑定线程到物理核心
        println!("cargo:rustc-env=OMP_PLACES=cores");
        println!("cargo:rustc-env=OMP_PROC_BIND=close");
        println!("cargo:rustc-env=GOTO_NUM_THREADS={}", num_cpus::get());
        println!("cargo:rustc-env=OPENBLAS_NUM_THREADS={}", num_cpus::get());
        // 启用 AVX-512 VNNI（Intel Deep Learning Boost）
        println!("cargo:rustc-env=OPENBLAS_LOOPS=avx512");
        // OpenBLAS 动态选择最优 kernel
        println!("cargo:rustc-env=OPENBLAS_MAIN_FREE=1");
        println!("cargo:rustc-env=OPENBLAS_VERBOSE=0");
    }

    for f in &sources {
        println!("cargo:rerun-if-changed={}", fortran_dir.join(f).display());
    }
    println!("cargo:rerun-if-changed=build.rs");
}
